# відкрити файл
import pandas as pd
df = pd.read_csv("top-rated-coffee-pp100g(enc).csv", sep=";", on_bad_lines="skip")

#print(df.columns.tolist())

column_to_show = ["roaster_location"]

# список локацій
# TODO: деякі локації повторюються через орфарграфічні помилки, слово місто зайве
normalize = [
    "Hilo, Hawai’i Island, Hawai’i",
    "Hilo, Hawai'i",
    "Chia-Yi, Taiwan",
    "Cleveland, Tennessee",
	"Jersey City, New Jersey",
	"Chia-Yi, Taiwan",
	"Taichung, Taiwan",
	"Yunlin, Taiwan",
	"Taipei, Taiwan",
	"Madison, Wisconsin",
	"Yilan, Taiwan",
	"Charlotte, North Carolina",
	"Peoria, Illinois",
	"Floyd, Virginia",
	"Hilo, Hawai’i Island, Hawai’i",
	"San Diego, California",
	"Fort Wayne, Indiana",
	"Hilo, Hawai'i",
	"Durango, Colorado",
	"Norfolk, Virginia",
	"Glendale, California",
	"Santa Fe, New Mexico",
	"Los Angeles, California",
	"Tulsa, Oklahoma",
	"Tainan, Taiwan",
	"Baronett, Wisconsin",
	"McHenry, Illinois",
	"Tiachung, Taiwan",
	"Kaohsiung, Taiwan",
	"Satipo Province, Peru",
	"New Taipei City, Taiwan",
	"Reno, Nevada",
	"Lexington, Virginia",
	"Taitung, Taiwan",
	"Manlius, New York",
	"Topeka, Kansas",
	"Mountain View, Hawai'i",
	"Denver, Colorado",
	"Antigua Guatemala, Guatemala",
	"Thermopolis, Wyoming",
	"Truckee, California",
	"Sacramento, Calfornia",
	"Sacramento, California",
	"Lee, Massachusetts",
	"Osaka, Japan",
	"Viroqua, Wisconsin",
	"Olympia, Washington",
	"Hilo, Hawai’i",
	"Barronett, Wisconsin",
	"Taoyuan, Taiwan",
	"Holualoa, Hawai’i",
	"Taipei City, Taiwan",
	"Chicago, Illinois",
	"Livingston, Montana",
	"Long Island City, New York",
	"Pahala, Hawaii",
	"Plymouth, Massachusetts",
	"Tainan City, Taiwan",
	"Zhubei, Taiwan",
	"Durham, North Carolina",
	"Caotun, Nantou, Taiwan",
	"Hilo, Hawaii",
	"Billings, Montana",
	"Buffalo, New York",
	"Conway, Arkansas",
	"Dallas, Texas",
	"Boulder, Colorado",
	"Holualoa, Hawaii",
	"Dali District, Taichung, Taiwan",
	"Columbus, Ohio",
	"Portland, Maine",
	"Berkeley, California",
	"Ashland, Oregon",
	"Mountain View, Hawai’i",
	"Kihei, Maui, Hawai’i",
	"Pahala, “Big Island” of Hawai’i",
	"Hsinchu, Taiwan",
	"Crystal Lake, Illinois",
	"San Jose, California",
	"San Rafael, California",
	"Hilo, Big Island of Hawai'i",
	"Richmond, Virginia",
	"Changhua, Taiwan",
	"Taiyuan, Taiwan",
	"Bozeman, Montana",
	"Johns Creek, Georgia",
	"Hilo, Big Island of Hawai’i",
	"Lake Forest, Illinois",
	"Seoul, South Korea",
	"Waterbury Center, Vermont",
	"Phoenix, Arizona",
	"Mount Shasta, California",
	"Nantou, Taiwan",
	"Minneapolis, Minnesota",
	"Savannah, Georgia",
	"Hong Kong, China",
	"Macao, China",
	"Redding, California",
	"Minnesota, Minnesota",
	"Big Lake, Alaska",
	"Rochester, New York",
	"Antigua, Guatemala",
	"Lincoln, California",
	"Montrose, Colorado",
	"Toronto, Canada",
	"Youngstown, Ohio",
	"Mountain View, Hawaii",
	"Manassas, Virginia",
	"Tucson, Arizona",
	"Miami, Florida",
	"Henderson, Nevada",
	"Ventura, California",
	"London, England",
	"Harrisonburg, Virginia",
	"Douliou City, Taiwan",
	"Taiwan",
	"Pahala, Hawai'i",
	"Kiambu County, Kenya",
	"Taoyuan City, Taiwan",
	"Chia-Yi City, Taiwan",
	"Martinez, California",
	"Chiya-Yi, Taiwan",
	"Branford Connecticut",
	"Albuquerque, New Mexico",
	"Tequesta, Florida",
	"Branford, Connecticut",
	"Washington, D.C.",
	"Pingtung, Taiwan",
	"Spokane, Washington",
	"Taichung City, Taiwan",
	"Houston, Texas",
	"Hamilton, Montana",
	"Suwanee, Georgia",
	"Bogota, Colombia",
	"Kaohsiung City, Taiwan",
	"Captain Cook, Hawai’i",
	"Lloydminster, Saskatchewan, Canada",
	"Llayla District, Satipo Province, Peru",
	"Keelung, Taiwan",
	"Captain Cook, Hawaii",
	"Toronto, Ontario, Canada",
	"Bedford, New Hampshire",
	"Carlsbad, California",
	"Santa Rosa Beach, Florida",
	"Ka'u, Hawaii",
	"Kihei, Maui, Hawaii",
	"Eugene, Oregon",
	"Renton, Washington",
	"Atlanta, Georgia",
	"Des Moines, Iowa",
	"Jackson, Mississippi",
	"Roanoke, Virginia and Floyd, Virginia",
	"San Francisco, California",
	"Carbondale, Colorado",
	"Fort Bragg, California",
	"Austin, Texas",
	"Jakarta, Indonesia",
	"Emeryville, California",
	"Newtown, Sydney, Australia",
	"Portland, Oregon",
	"Santa Monica, California",
	"I-Lan City, Taiwan",
	"Charlottesville, Virginia",
	"San Juan Lachao, Oaxaca, Mexico",
	"Silver Lake, Minnesota",
	"Shanghai, China",
	"Vancouver, British Columbia, Canada",
	"Boston, Massachusetts",
	"Minxiong, Chia-Yi, Taiwan",
	"Belmar, New Jersey",
	"Brooklyn, New York",
	"Changhua County, Taiwan",
	"Hillsborough, North Carolina",
	"Sacramento, Californiaa",
	"Sacamento, California",
	"Zhubei City, Taiwan",
	"Thornton, Colorado",
	"Ramsey, Minnesota",
	"Louisville, Kentucky",
	"Oakville, Ontario, Canada",
	"Torrington, Connecticut",
	"Chino, California",
	"Daejeon, South Korea",
	"Kaohslung City, Taiwan",
	"Markham, Ontario, Canada",
	"Holulaloa, Hawaii",
	"St. Louis, MIssouri",
	"Seattle, Washington",
	"Driftless, Wisconsin",
	"Newport Beach, California",
	"Duluth, Minnesota",
	"Fort Lauderdale, Florida",
	"Washington, DC",
	"Burlington, Vermont",
	"Yongin-Si, South Korea",
	"Pu'Er Yunnan Province, China",
	"Suzhou, China",
	"New Orleans, Louisiana",
	"Post Falls, Idaho",
	"Santa Ana growing region, El Salvador",
	"Ovledo, Florida",
	"La Jolla, California",
	"Lake, Michigan",
	"Hsinchu City, Taiwan",
	"Pu’Er, Yunnan Province, China",
	"Yorktown Heights, New York",
	"Highland Park, New Jersey",
	"Paju City (Gyeonggi-do), South Korea",
	"Longwood, Florida",
	"Bellingham, Washington",
	"Billings, Montana.",
	"Oakland, California",
	"San Luis Obispo, California",
	"South Korea",
	"Sacr",
	"Kowloon, Hong Kong, China",
	"Redlands, California",
	"Raleigh, North Carolina",
	"Cambria, California",
	"Seoul, Korea",
	"Everett, Washington",
	"Berlin, Massachusetts",
	"Calgary, Alberta, Canada",
	"Anchorage, Alaska",
	"Acton, Massachusetts",
	"Annapolis, Maryland",
	"Waterbury, Vermont",
	"New Brunswick, New Jersey",
	"Taoyuan City, Taiwan.",
	"Lexington, Virginia.",
	"Madison, Wisconsin.",
	"Sioux Falls, South Dakota",
	"Upland, California",
	"Hudson, New York",
	"Ithaca, New York",
	"London, Ontario, Canada",
	"Salem, Massachusetts",
	"Richmond, British Columbia, Canada",
	"Richmond Hill, Ontario, Canada",
	"Kansas City, Missouri",
	"Arlington, Massachusetts",
	"San Dimas, California",
	"Beverly, Massachusetts",
	"Anoka, Minnesota",
	"North Hollywood, California",
	"Milwaukee, Wisconsin",
	"Philadelphia, Pennsylvania",
	"Arcata, California",
	"Langhorne, Pennsylvania",
	"Boise, Idaho",
	"Fairbanks, Alaska",
	"New Haven, Connecticut",
	"Lake Tahoe, California",
	"Maui, Hawaii"
]

# умовне виконання 
def clean_name(name):
    name = name.lower()
    if "County" in name:
        name = name.replace("County", "")
    if "City" in name:
        name = name.replace("City", "")
    if "District" in name:
        name = name.replace("District", "")
    if "." in name:
        name = name.replace(".", "")
    if "rowing region" in name:
        name = name.replace("growing region", "")    
    if "Hawai’i Island," in name:
        name = name.replace("Hawai’i Island,", " ")    
    return name.strip()
    
#
df["clean_location"] = df["roaster_location"].apply(clean_name)

# зберегти результат у новий файл
df.to_csv("location_clean.csv", index=False)
print("Файл збережено як location_clean.csv")
 
# парсинг локацій
# TODO: не всі останні записи - країни, деякі штати
#def parse_location(s):
#   parts = [p.strip() for p in s.split(',')]
#    if len(parts) == 1:
#        return [parts[0], '']         #  місто
#    else:
#        city = parts[0]
#        country = parts[-1]           # остання частина як країна
#        return [city, country]

#parsed = [parse_location(x) for x in data]

